[package]
name = "cachedirtree"
version = "0.2.1"
authors = ["Ivan <ivan.zderadicka@gmail.com>"]

[dependencies]
ego-tree="0.6"
bit-vec = "0.6"
notify = "4.0"
derive_builder = "0.9"


[dependencies.log]
version = "0.4"


[dev-dependencies]
env_logger = "0.8"

[features]
default=["symlinks"]
symlinks=[]
