[package]
name = "media_info"
version = "0.1.4"
authors = ["Ivan <ivan.zderadicka@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
thiserror = "1.0"


[features]
static=[]
partially-static=[]

